<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>9b002773-d728-4896-bb27-d2e147847d91</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "2 - Standard" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
